WebApp/Controllers/ApplicationRolesController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Authorize(Policy = "ManageRoles")]
    public class ApplicationRolesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;

        public ApplicationRolesController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<ApplicationRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        // GET: ApplicationRoles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }


        // GET: ApplicationRoles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole applicationRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            ApplicationRoleViewModel viewModel =
                await GetRolesViewModelFromRole(applicationRole);

            return View(viewModel);
        }


        // Post: ApplicationRoles/Details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(ApplicationRoleViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            // Add user to new role and remove from old
            ApplicationUser user =
                await _userManager.FindByNameAsync(viewModel.UserName);

            // If no user, do nothing.
            if (user == null) return View(viewModel);

            IList<string> currentRoles = await _userManager.GetRolesAsync(user);
            await _userManager.AddToRoleAsync(user, viewModel.Role);
            foreach (string currentRole in currentRoles)
            {
                await _userManager.RemoveFromRoleAsync(user, currentRole);
            }

            // Add the claim
            await _userManager.AddClaimAsync(user,
                new Claim(viewModel.Role, "True"));

            // Save changes to database
            await _context.SaveChangesAsync();

            // Create view from role
            ApplicationRole role =
                await _roleManager.FindByNameAsync(viewModel.Role);
            viewModel = await GetRolesViewModelFromRole(role);

            return View(viewModel);
        }


        // Get an Application Roles view model from a given role.
        private async Task<ApplicationRoleViewModel> GetRolesViewModelFromRole(
            ApplicationRole applicationRole)
        {
            var viewModel = new ApplicationRoleViewModel
            {
                ApplicationRole = applicationRole
            };

            /*IList<ApplicationUser> roleUsers = await
                _userManager.GetUsersInRoleAsync(applicationRole.ToString());*/
            IList<ApplicationUser> roleUsers = await
                _userManager.GetUsersForClaimAsync(
                    new Claim(applicationRole.Name, "True"));

            viewModel.ApplicationUsers = roleUsers;

            return viewModel;
        }


        // GET: ApplicationRoles/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: ApplicationRoles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Description")] string name, string description)
        {
            var applicationRole = new ApplicationRole
            {
                Name = name,
                Description = description
            };
            if (!ModelState.IsValid) return View(applicationRole);

            _context.Add(applicationRole);
            await _roleManager.CreateAsync(applicationRole);
            await _roleManager.SetRoleNameAsync(applicationRole, name);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: ApplicationRoles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole applicationRole = await _context.Roles.FindAsync(id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            return View(applicationRole);
        }


        // POST: ApplicationRoles/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id, Name, Description")] string id, string name,
            string description)
        {
            // Get the role and change the name(s)
            ApplicationRole role = await _roleManager.FindByIdAsync(id);
            string oldName = role.Name;
            if (name != null)
            {
                role.Name = name;
                role.NormalizedName = name.Normalize();
                // Update claim name for all users who have it
                await UpdateClaim(name, oldName);
            }

            // Add description if there is one
            if (!string.IsNullOrEmpty(description))
            {
                role.Description = description;
            }

            _context.Update(role);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // GET: ApplicationRoles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole applicationRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            return View(applicationRole);
        }


        // POST: ApplicationRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            // Get role name and remove role
            ApplicationRole applicationRole = await _context.Roles.FindAsync(id);
            string name = applicationRole.Name;

            // Remove claim for all users who have it, and remove role.
            await RemoveClaim(name);
            _context.Roles.Remove(applicationRole);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private async Task UpdateClaim(string newName, string oldName)
        {
            // Get all users with the claim and update them
            var oldClaim = new Claim(oldName, "True");
            var newClaim = new Claim(newName, "True");
            IList<ApplicationUser> usersWithClaim =
                await _userManager.GetUsersForClaimAsync(oldClaim);
            foreach (ApplicationUser user in usersWithClaim)
            {
                await _userManager.RemoveClaimAsync(user, oldClaim);
                await _userManager.AddClaimAsync(user, newClaim);
            }
        }


        private async Task RemoveClaim(string name)
        {
            // Remove the claim from all user who have it
            var claim = new Claim(name, "True");
            IList<ApplicationUser> usersInClaim =
                await _userManager.GetUsersForClaimAsync(claim);
            await _userManager.GetUsersForClaimAsync(claim);
            foreach (ApplicationUser user in usersInClaim)
            {
                await _userManager.RemoveClaimAsync(user, claim);
            }
        }
    }
}

WebApp/Controllers/ApplicationUsersController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Authorize(Policy = "ManageUsers")]
    public class ApplicationUsersController : Controller
    {
        private static ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ApplicationUsersController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Username, Email, FirstName, LastName, Password, PasswordConfirm")]
            string username, string firstName, string lastName, string email,
            string password, ApplicationUserViewModel applicationUserView)
        {
            if (!ModelState.IsValid) return View(applicationUserView);

            var applicationUser = new ApplicationUser
            {
                UserName = username,
                Email = email,
                FirstName = firstName,
                LastName = lastName
            };

            IdentityResult result = await _userManager.CreateAsync(
                applicationUser, password);
            if (result.Succeeded)
            {
                // Add default role and claim
                await _userManager.AddToRoleAsync(applicationUser, "Customer");
                await _userManager.AddClaimAsync(applicationUser,
                    new Claim("Customer", "True"));
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // Get: ApplicationUser/Edit
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser applicationUser = await _context.Users.FindAsync(id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }


        // POST: ApplicationUser/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            [Bind("UserName, Email, FirstName, LastName")]
            string id, string userName, string firstName, string lastName)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            user.UserName = userName;
            user.NormalizedUserName = userName.Normalize();
            user.FirstName = firstName;
            user.LastName = lastName;

            _context.Update(user);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // Get: ApplicationUsers/Details
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser viewModel = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }


        // Post: ApplicationUsers/Details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(ApplicationUser viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);
            viewModel = await _userManager.FindByNameAsync(viewModel.UserName);
            return View(viewModel);
        }


        // GET: ApplicationUser/Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser applicationUser = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }


        // POST: ApplicationUser/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = await _context.Users.FindAsync(id);
            _context.Users.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Pages/Edit.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Pages
{
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "EditArticle")]
    public class EditModel : PageModel
    {
        private readonly ArticleStorage _dataStore;
        private readonly ExcerptGenerator _excerptGenerator;
        private readonly HtmlEncoder _htmlEncoder;

        public EditModel(ArticleStorage dataStore,
            ExcerptGenerator excerptGenerator, HtmlEncoder htmlEncoder)
        {
            _dataStore = dataStore;
            _excerptGenerator = excerptGenerator;
            _htmlEncoder = htmlEncoder;
        }

        [BindProperty] public EditedArticleModel EditedArticle { get; set; }

        public bool HasSlug { get; set; }


        public void OnGet([FromRoute] string id)
        {
            Article article = _dataStore.GetArticle(id);

            if (article == null)
            {
                RedirectToPage("/Index");
            }
            else
            {
                EditedArticle = new EditedArticleModel
                {
                    Title = article.Title,
                    Body = article.Body,
                    Excerpt = article.Excerpt
                };

                HasSlug = !string.IsNullOrEmpty(article.Slug);

                string iDNoHyphens = article.Id.ToString()
                    .Replace("-", "");
                ViewData["Slug"] = article.Slug;
                ViewData["id"] = iDNoHyphens;
            }
        }


        public IActionResult OnPostPublish([FromRoute] string id,
            [FromForm] bool updateSlug)
        {
            string safeId = _htmlEncoder.Encode(id);
            Article article = _dataStore.GetArticle(safeId);
            if (!ModelState.IsValid)
            {
                return LocalRedirect("/article/" + safeId + "/" + article.Slug);
            }

            bool wasPublic = article.IsPublic;
            article.IsPublic = true;
            if (article.PubDate.Equals(default(DateTimeOffset)))
            {
                article.PubDate = DateTimeOffset.Now;
            }

            if (!HasSlug)
            {
                article.Slug = SlugGenerator.CreateSlug(article.Title);
            }

            UpdateArticle(article, updateSlug, wasPublic);

            return LocalRedirect("/article/" + safeId + "/" + article.Slug);
        }


        public IActionResult OnPostSaveDraft([FromRoute] string id)
        {
            string safeId = _htmlEncoder.Encode(id);
            Article article = _dataStore.GetArticle(safeId);
            if (!ModelState.IsValid) return LocalRedirect("/Drafts");

            bool wasPublic = article.IsPublic;
            article.IsPublic = false;
            UpdateArticle(article, false, wasPublic);

            return LocalRedirect("/Drafts");
        }


        private void UpdateArticle(Article article, [FromForm] bool updateSlug,
            bool wasPublic)
        {
            article.Title = EditedArticle.Title;
            article.Body = EditedArticle.Body;
            if (string.IsNullOrEmpty(EditedArticle.Excerpt))
            {
                EditedArticle.Excerpt =
                    _excerptGenerator.CreateExcerpt(EditedArticle.Body);
            }

            article.Excerpt = EditedArticle.Excerpt;

            if (updateSlug)
            {
                article.Slug = SlugGenerator.CreateSlug(article.Title);
            }

            if (Request != null)
            {
                _dataStore.SaveFiles(Request.Form.Files.ToList());
            }

            _dataStore.UpdateArticle(article, wasPublic);
        }


        public class EditedArticleModel
        {
            [Required] public string Title { get; set; }
            [Required] public string Body { get; set; }
            public string Excerpt { get; set; }
        }
    }
}

WebApp/Views/ApplicationUsers/Create.cshtml
@model WebApp.Models.ApplicationUserViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Application User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*Username*@
            <div class="form-group">
                <label asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control"/>
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            @*Email*@
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            @*First Name*@
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control"/>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            @*Last Name*@
            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control"/>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            @*Password*@
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" type="password"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            @*Password Confirm*@
            <div class="form-group">
                <label asp-for="PasswordConfirm"></label>
                <input asp-for="PasswordConfirm" class="form-control" type="password"/>
                <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/ApplicationUsers/Delete.cshtml
@model WebApp.Models.ApplicationUser

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Application User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Views/ApplicationUsers/Details.cshtml
@model ApplicationUser

@{
    ViewData["Title"] = "Details";
}

@* Display user details*@
<h1>Details</h1>
<table class="table">
    <thead>
    <tr>
        <th>
            ID
        </th>
        <th>
            Username
        </th>
        <th>
            Email
        </th>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.LastName)
        </td>
    </tr>
    </tbody>
</table>

@* Edit, delete, or go back*@
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/ApplicationUsers/Edit.cshtml
@model WebApp.Models.ApplicationUser

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Application User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @* Username *@
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            @* Email *@
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            @* First Name *@
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            @* Last Name  *@
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            @* Submit *@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/ApplicationUsers/Index.cshtml
@model IEnumerable<WebApp.Models.ApplicationUser>
@inject IAuthorizationService AuthorizationService
@using Microsoft.AspNetCore.Authorization

@{
    ViewData["Title"] = "Index";
}

<h1>Manage Users</h1>

@* Only admins can create new users. *@
@if (User.HasClaim("Member", "True"))
{
    <div class="container-fluid mb-2">
        <div class="row-fluid">
            @* Add a new user *@
            <a asp-action="Create">
                <button type="button"
                        class="btn btn-primary text-light">
                    New User
                </button>
            </a>
            @* Go to Application Roles area *@
            @if ((await AuthorizationService.AuthorizeAsync(
                User, "ManageRoles")).Succeeded)
            {
                <a asp-controller="ApplicationRoles" asp-action="Index">
                    <button type="button"
                            class="btn btn-primary text-light">
                        Manage Roles
                    </button>
                </a>
            }
        </div>
    </div>
}

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (ApplicationUser item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">View & Manage</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>