WebApp/Controllers/ApplicationRolesController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Authorize(Policy = "ManageRoles")]
    public class ApplicationRolesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;

        public ApplicationRolesController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<ApplicationRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        // GET: ApplicationRoles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }


        // GET: ApplicationRoles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole applicationRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            ApplicationRoleViewModel viewModel =
                await GetRolesViewModelFromRole(applicationRole);

            return View(viewModel);
        }


        // Post: ApplicationRoles/Details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(ApplicationRoleViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            // Add user to new role and remove from old
            ApplicationUser user =
                await _userManager.FindByNameAsync(viewModel.UserName);

            // If no user, do nothing.
            if (user == null) return View(viewModel);

            IList<string> currentRoles = await _userManager.GetRolesAsync(user);
            await _userManager.AddToRoleAsync(user, viewModel.Role);
            foreach (string currentRole in currentRoles)
            {
                await _userManager.RemoveFromRoleAsync(user, currentRole);
            }

            // Add the claim
            await _userManager.AddClaimAsync(user,
                new Claim(viewModel.Role, "True"));

            // Save changes to database
            await _context.SaveChangesAsync();

            // Create view from role
            ApplicationRole role =
                await _roleManager.FindByNameAsync(viewModel.Role);
            viewModel = await GetRolesViewModelFromRole(role);

            return View(viewModel);
        }


        // Get an Application Roles view model from a given role.
        private async Task<ApplicationRoleViewModel> GetRolesViewModelFromRole(
            ApplicationRole applicationRole)
        {
            var viewModel = new ApplicationRoleViewModel
            {
                ApplicationRole = applicationRole
            };

            /*IList<ApplicationUser> roleUsers = await
                _userManager.GetUsersInRoleAsync(applicationRole.ToString());*/
            IList<ApplicationUser> roleUsers = await
                _userManager.GetUsersForClaimAsync(
                    new Claim(applicationRole.Name, "True"));

            viewModel.ApplicationUsers = roleUsers;

            return viewModel;
        }


        // GET: ApplicationRoles/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: ApplicationRoles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Description")] string name, string description)
        {
            var applicationRole = new ApplicationRole
            {
                Name = name,
                Description = description
            };
            if (!ModelState.IsValid) return View(applicationRole);

            _context.Add(applicationRole);
            await _roleManager.CreateAsync(applicationRole);
            await _roleManager.SetRoleNameAsync(applicationRole, name);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: ApplicationRoles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole applicationRole = await _context.Roles.FindAsync(id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            return View(applicationRole);
        }


        // POST: ApplicationRoles/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id, Name, Description")] string id, string name,
            string description)
        {
            // Get the role and change the name(s)
            ApplicationRole role = await _roleManager.FindByIdAsync(id);
            string oldName = role.Name;
            if (name != null)
            {
                role.Name = name;
                role.NormalizedName = name.Normalize();
                // Update claim name for all users who have it
                await UpdateClaim(name, oldName);
            }

            // Add description if there is one
            if (!string.IsNullOrEmpty(description))
            {
                role.Description = description;
            }

            _context.Update(role);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // GET: ApplicationRoles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole applicationRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            return View(applicationRole);
        }


        // POST: ApplicationRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            // Get role name and remove role
            ApplicationRole applicationRole = await _context.Roles.FindAsync(id);
            string name = applicationRole.Name;

            // Remove claim for all users who have it, and remove role.
            await RemoveClaim(name);
            _context.Roles.Remove(applicationRole);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private async Task UpdateClaim(string newName, string oldName)
        {
            // Get all users with the claim and update them
            var oldClaim = new Claim(oldName, "True");
            var newClaim = new Claim(newName, "True");
            IList<ApplicationUser> usersWithClaim =
                await _userManager.GetUsersForClaimAsync(oldClaim);
            foreach (ApplicationUser user in usersWithClaim)
            {
                await _userManager.RemoveClaimAsync(user, oldClaim);
                await _userManager.AddClaimAsync(user, newClaim);
            }
        }


        private async Task RemoveClaim(string name)
        {
            // Remove the claim from all user who have it
            var claim = new Claim(name, "True");
            IList<ApplicationUser> usersInClaim =
                await _userManager.GetUsersForClaimAsync(claim);
            await _userManager.GetUsersForClaimAsync(claim);
            foreach (ApplicationUser user in usersInClaim)
            {
                await _userManager.RemoveClaimAsync(user, claim);
            }
        }
    }
}

WebApp/Pages/Article.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Pages
{
    [ValidateAntiForgeryToken]
    public class ArticleModel : PageModel
    {
        private readonly ArticleStorage _dataStore;
        private readonly HtmlEncoder _htmlEncoder;
        private const int MaxAllowedComments = 100;

        public ArticleModel(ArticleStorage dataStore, HtmlEncoder htmlEncoder)
        {
            _dataStore = dataStore;
            _htmlEncoder = htmlEncoder;
        }

        
        public Article Article { get; set; }

        
        public bool IsCommentsFull => Article.Comments.Count >= MaxAllowedComments;

        
        public HtmlString HtmlBody()
        {
            HtmlString html = MarkdownRenderer.RenderMarkdown(Article.Body);
            return html;
        }

        
        public void OnGet([FromRoute] string id)
        {
            Article = _dataStore.GetArticle(id);

            if (Article == null || !Article.IsPublic)
            {
                RedirectToPage("/Index");
            }
        }


        private IActionResult ChangeState(bool deleted, string id)
        {
            Article = _dataStore.GetArticle(id);

            if (!ModelState.IsValid)
                return LocalRedirect("/article/" + id + "/" + Article.Slug);

            Article.IsDeleted = deleted;
            _dataStore.SaveArticle(Article);
            return RedirectToPage("/Index");
        }


        public IActionResult OnPostDeleteArticle([FromRoute] string id)
        {
            string safeId = _htmlEncoder.Encode(id);
            return ChangeState(true, safeId);
        }

        

        public IActionResult OnPostUnDeleteArticle([FromRoute] string id)
        {
            string safeId = _htmlEncoder.Encode(id);
            return ChangeState(false, safeId);
        }


        public IActionResult OnPostPublishComment([FromRoute] string id,
            [FromForm] CommentViewModel newComment)
        {
            string safeId = _htmlEncoder.Encode(id);
            Article = _dataStore.GetArticle(safeId);

            if (Article == null)
            {
                return RedirectToPage("/Index");
            }

            if (!ModelState.IsValid) return Page();
            var comment = new Comment
            {
                Author = newComment.Author,
                Body = newComment.Body,
                IsPublic = true,
                UniqueId = Guid.NewGuid()
            };
            Article.Comments.Add(comment);
            _dataStore.SaveArticle(Article);

            return LocalRedirect("/article/" + safeId + "/" + Article.Slug);
        }
        
        
        public IActionResult OnPostDeleteComment(Guid commentId, string id)
        {
            string safeId = _htmlEncoder.Encode(id);
            Article article = _dataStore.GetArticle(safeId);

            Comment foundComment = ArticleStorage.FindComment(commentId, article);
            foundComment.IsPublic = false;

            _dataStore.SaveArticle(article);
            
            return LocalRedirect("/article/" + safeId + "/" + article.Slug);
        }


        public IActionResult OnPostUnDeleteComment(Guid commentId, string id)
        {           
            string safeId = _htmlEncoder.Encode(id);
            Article article = _dataStore.GetArticle(safeId);

            Comment foundComment = ArticleStorage.FindComment(commentId, article);
            foundComment.IsPublic = true;

            _dataStore.SaveArticle(article);

            return LocalRedirect("/article/" + safeId + "/" + article.Slug);
        }


        public class CommentViewModel
        {
            [Required]
            [MaxLength(100, ErrorMessage = "You have exceeded the maximum " +
                                           "length of 100 characters")]
            public string Author { get; set; }

            [Required]
            [MaxLength(1000, ErrorMessage = "You have exceeded the maximum " +
                                            "length of 1000 characters")]
            public string Body { get; set; }
        }
    }
}

WebApp/Pages/Edit.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Pages
{
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "EditArticle")]
    public class EditModel : PageModel
    {
        private readonly ArticleStorage _dataStore;
        private readonly ExcerptGenerator _excerptGenerator;
        private readonly HtmlEncoder _htmlEncoder;

        public EditModel(ArticleStorage dataStore,
            ExcerptGenerator excerptGenerator, HtmlEncoder htmlEncoder)
        {
            _dataStore = dataStore;
            _excerptGenerator = excerptGenerator;
            _htmlEncoder = htmlEncoder;
        }

        [BindProperty] public EditedArticleModel EditedArticle { get; set; }

        public bool HasSlug { get; set; }


        public void OnGet([FromRoute] string id)
        {
            Article article = _dataStore.GetArticle(id);

            if (article == null)
            {
                RedirectToPage("/Index");
            }
            else
            {
                EditedArticle = new EditedArticleModel
                {
                    Title = article.Title,
                    Body = article.Body,
                    Excerpt = article.Excerpt
                };

                HasSlug = !string.IsNullOrEmpty(article.Slug);

                string iDNoHyphens = article.Id.ToString()
                    .Replace("-", "");
                ViewData["Slug"] = article.Slug;
                ViewData["id"] = iDNoHyphens;
            }
        }


        public IActionResult OnPostPublish([FromRoute] string id,
            [FromForm] bool updateSlug)
        {
            string safeId = _htmlEncoder.Encode(id);
            Article article = _dataStore.GetArticle(safeId);
            if (!ModelState.IsValid)
            {
                return LocalRedirect("/article/" + safeId + "/" + article.Slug);
            }

            bool wasPublic = article.IsPublic;
            article.IsPublic = true;
            if (article.PubDate.Equals(default(DateTimeOffset)))
            {
                article.PubDate = DateTimeOffset.Now;
            }

            if (!HasSlug)
            {
                article.Slug = SlugGenerator.CreateSlug(article.Title);
            }

            UpdateArticle(article, updateSlug, wasPublic);

            return LocalRedirect("/article/" + safeId + "/" + article.Slug);
        }


        public IActionResult OnPostSaveDraft([FromRoute] string id)
        {
            string safeId = _htmlEncoder.Encode(id);
            Article article = _dataStore.GetArticle(safeId);
            if (!ModelState.IsValid) return LocalRedirect("/Drafts");

            bool wasPublic = article.IsPublic;
            article.IsPublic = false;
            UpdateArticle(article, false, wasPublic);

            return LocalRedirect("/Drafts");
        }


        private void UpdateArticle(Article article, [FromForm] bool updateSlug,
            bool wasPublic)
        {
            article.Title = EditedArticle.Title;
            article.Body = EditedArticle.Body;
            if (string.IsNullOrEmpty(EditedArticle.Excerpt))
            {
                EditedArticle.Excerpt =
                    _excerptGenerator.CreateExcerpt(EditedArticle.Body);
            }

            article.Excerpt = EditedArticle.Excerpt;

            if (updateSlug)
            {
                article.Slug = SlugGenerator.CreateSlug(article.Title);
            }

            if (Request != null)
            {
                _dataStore.SaveFiles(Request.Form.Files.ToList());
            }

            _dataStore.UpdateArticle(article, wasPublic);
        }


        public class EditedArticleModel
        {
            [Required] public string Title { get; set; }
            [Required] public string Body { get; set; }
            public string Excerpt { get; set; }
        }
    }
}

WebApp/Pages/Article.cshtml
@page "{id}/{slug}"
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model WebApp.Pages.ArticleModel
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    ViewData["Title"] = Model.Article.Title;
}

<article>
<div class="col-md-12">
    <h1>@Model.Article.Title</h1>
    @if (!string.IsNullOrEmpty(Model.Article.Author))
    {
        <h4 name="author" class="text-muted">By @Model.Article.Author </h4>
    }
    <h5 name="date" class="date text-muted">
        @Model.Article.PubDate.ToString(
            "MMM dd, yyyy")</h5>
    <p>@Model.HtmlBody()</p>
</div>

@if ((await AuthorizationService.AuthorizeAsync(User, "MemberOnly")).Succeeded)
{
    if ((await AuthorizationService.AuthorizeAsync(User, "EditArticle")).Succeeded)
    {
        /* Edit */
        <div class="col-md-12">
            <h4 class="text-primary">
                <a asp-page="/edit"
                   asp-route-id="@Model.Article.Id.ToString("N")"
                   asp-route-slug="@Model.Article.Slug">
                    Edit Article
                </a>
            </h4>
        </div>
    }
    if ((await AuthorizationService.AuthorizeAsync(
        User, "DeleteArticle")).Succeeded)
    {
        /* Delete */
        <form class="col-md-12" id="deletearticle" method="post">
            @if (Model.Article.IsDeleted)
            {
                <div>
                    <input type="submit" name="undelete"
                           class="btn btn-primary btn-sm" value="Undelete"
                           asp-page-handler="UnDeleteArticle"/>
                </div>
            }
            else
            {
                <div>
                    <input type="submit" name="delete" class="btn btn-primary btn-sm"
                           value="Delete" asp-page-handler="DeleteArticle"/>
                </div>
            }
        </form>
    }
    <div class="col-md-6">
        <h2>Comments</h2>
        @if (Model.Article.Comments.Count == 0)
        {
            <p class="text-muted">No comments yet. Be the first to comment!</p>
        }
        @foreach (Comment comment in Model.Article.Comments)
        {
            string cssClass = comment.IsPublic ? "" : "deletedContent";
            <form id="form1" method="post">
                <div class="@cssClass">
                    @if (comment.IsPublic)
                    {
                        <div class="well well-sm">
                            @* Author *@
                            <h4 name="Comment-Title" class="commentTitle">
                                @comment.Author
                            </h4>
                            @* Date *@
                            <h6 name="Comment-Date" class="commentDate">
                                @comment.Created.ToString("dd MMM, yyyy")
                            </h6>
                            @* Body *@
                            <p name="Comment-Body" class="commentBody">
                                @comment.Body
                            </p>
                            @* Id *@
                            <input type="hidden" name="commentId" id="commentId"
                                   value="@comment.UniqueId"/>
                            @* Slug *@
                            <input type="hidden" name="slug"
                                   value="@Model.Article.Slug"/>
                            @if ((await AuthorizationService.AuthorizeAsync(
                                User, "DeleteAnyComment")).Succeeded)
                            {
                                    @* Delete comment *@
                                <input type="submit" name="delete"
                                       class="btn btn-primary btn-sm"
                                       value="Delete Comment"
                                       asp-page="Article"
                                       asp-page-handler="DeleteComment"/>
                            }
                        </div>
                    }
                    else
                    {
                        <div class="well well-sm">
                            <del class="h4">
                                @* Author *@
                                <h4 name="Comment-Title" class="commentTitle">
                                    @comment.Author
                                </h4>
                                @* Date *@
                                <h6 name="Comment-Date" class="commentDate">
                                    @comment.Created.ToString("dd MMM, yyyy")
                                </h6>
                            </del>
                            @* Deleted body *@
                            <del>
                                <p name="Comment-Body" class="commentBody">
                                    @comment.Body
                                </p>
                            </del>
                            @* Id *@
                            <input type="hidden" name="commentId" id="commentId"
                                   value="@comment.UniqueId"/>
                            @* Slug *@
                            <input type="hidden" name="slug" v
                                   alue="@Model.Article.Slug"/>
                            @if ((await AuthorizationService.AuthorizeAsync(
                                User, "DeleteAnyComment")).Succeeded)
                            {
                                @* Undelete *@
                                <input type="submit" name="unDelete"
                                       class="btn btn-primary btn-sm"
                                       value="Republish Comment"
                                       asp-page="Article"
                                       asp-page-handler="UndeleteComment"/>
                            }
                        </div>
                    }
                </div>
            </form>
        }
    </div>
}
else
{
    <div class="col-md-6">
        <h2>Comments</h2>
        @if (Model.Article.Comments.Count == 0 &&
             (await AuthorizationService.AuthorizeAsync(
                 User, "CustomerOnly")).Succeeded)
        {
            <p class="text-muted">No comments <i>yet</i>.</p>
        }
        @foreach (Comment comment in Model.Article.Comments)
        {
            if (comment.IsPublic)
            {
                <form id="form1" method="post">
                    <div class="well well-sm">
                        <h4 name="Comment-Title" class="commentTitle">
                            @comment.Author
                        </h4>
                        <h6 name="Comment-Date" class="commentDate">
                            @comment.Created.ToString("MMM dd, yyyy")
                        </h6>
                        <p name="Comment-Body" class="commentBody">
                            @comment.Body
                        </p>
                        <input type="hidden" name="commentId" id="commentId"
                               value="@comment.UniqueId"/>
                        <input type="hidden" name="slug"
                               value="@Model.Article.Slug"/>
                        @* If user owns the comment and has deleteOwn claim,
                             OR has the deleteAny claim.*@
                        @if (User.Identity.Name == comment.Author &&
                             (await AuthorizationService.AuthorizeAsync(
                                 User, "DeleteOwnComment")).Succeeded
                             || (await AuthorizationService.AuthorizeAsync(
                                 User, "DeleteAnyComment")).Succeeded)
                        {
                            <input type="submit" name="delete"
                                   class="btn btn-primary btn-sm"
                                   value="Delete Comment"
                                   asp-page="Article"
                                   asp-page-handler="DeleteComment"/>
                        }
                    </div>
                </form>
            }
        }
    </div>
}

<hr/>

@if (Model.Article.IsPublic && !Model.IsCommentsFull
     && (await AuthorizationService.AuthorizeAsync(
         User, "CreateComment")).Succeeded)
{
    <div class="col-sm-6" style="height: 6px;"></div>
    <div class="add-comment-form">
        <div class="col-md-6">
            <h3>Add Comment</h3>

            <div class="well">
                <form id="comment-form" method="post">
                    @* User Name *@
                    <input type="hidden" class="form-control" placeholder="Anonymous"
                           name="NewComment.Author" value="@User.Identity.Name"/>
                    @* Body *@
                    <div class="form-group">
                        <label for="Body">Comment</label>
                        <textarea placeholder="Your comment here..." 
                                        class="form-control" 
                                            name="NewComment.Body"></textarea>
                    </div>
                    @* Publish *@
                    <input type="submit" name="publish"
                           class="btn btn-primary btn-sm" value="Publish"
                           asp-page-handler="PublishComment"/>
                </form>
            </div>
        </div>
    </div>
}
</article>

WebApp/Pages/Edit.cshtml
@page "{id}"
@model WebApp.Pages.EditModel
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    ViewData["Title"] = "Edit Article";
}

<article>
    <h2>Edit Article</h2>
    <div class="col-md-12 well">
        <form method="post" id="editarticle" enctype="multipart/form-data"
              data-has-slug="@Model.HasSlug">
            @if (TempData["notice"] != null)
            {
                <h3>@TempData["notice"]</h3>
            }
            @* Title *@
            <div class="form-group col-md-6">
                <label for="Title">Title</></label>
                <input type="text" class="form-control" placeholder=""
                       asp-for="EditedArticle.Title"
                       data-oldtitle="@Model.EditedArticle.Title"/>
                <span asp-validation-for="EditedArticle.Title" class="text-warning"></span>
            </div>
            @* Slug *@
            <input type="hidden" name="updateSlug" id="updateSlug" value="false"/>
            @* Body *@
            <div class="col-md-12 form-group">
                <label for="Body" class="primaryField">Body</label>
                <textarea rows="10" class="form-control" placeholder="" 
                            asp-for="EditedArticle.Body" id="article-body"></textarea>
                <span asp-validation-for="EditedArticle.Body"
                      class="text-warning">
                </span>
            </div>
            @* Excerpt *@
            <div class="col-md-12 form-group">
                <label for="Excerpt" class="secondaryField">Excerpt (Optional)</label>
                <textarea class="form-control" placeholder="" 
                            asp-for="EditedArticle.Excerpt"></textarea>
            </div>
            <div class="col-md-12">
                @* Save draft *@
                <input type="submit" name="save" class="btn btn-primary btn-sm"
                       value="Save Draft" asp-page-handler="SaveDraft"/>
                @* Publish *@
                <input type="submit" name="publish" id="articlesave" 
                       class="btn btn-primary btn-sm"
                       value="Publish" asp-page-handler="Publish"/>
            </div>
            @* Cancel and go back *@
            <div class="col-md-12">
                <p class="cancel-link">
                    <a asp-page="/article" asp-route-id="@ViewData["id"]"
                       asp-route-slug="@ViewData["Slug"]">
                        <span class="glyphicon glyphicon-triangle-left"></span> 
                        Cancel Changes
                    </a>
                </p>
            </div>
        </form>
    </div>
</article>

@section Scripts
{
}

WebApp/Pages/New.cshtml
@page
@model WebApp.Pages.NewModel
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    ViewData["Title"] = "New Blog Article";
}

<h2>Write a New Article</h2>

<form method="POST" enctype="multipart/form-data">
    <div class="col-md-12 well">
        @* Author *@
        <input type="hidden" class="form-control" placeholder=""
               name="NewArticle.Author"
               asp-for="NewArticle.Author" value="@User.Identity.Name" />
        @* Title *@
        <div class="form-group col-md-6">
            <label for="Title">Title</></label>
            <input type="text" class="form-control" placeholder=""
                   asp-for="NewArticle.Title"/>
            <span asp-validation-for="NewArticle.Title" class="text-warning"></span>
        </div>
        @* Body *@
        <div class="form-group col-md-12">
            <label for="Body" class="primaryField">Body</label>
            <textarea rows="10" class="form-control" placeholder="" 
            asp-for="NewArticle.Body" id="article-body"></textarea>
            <span asp-validation-for="NewArticle.Body" class="text-warning"></span>
        </div>
        @* Excerpt*@
        <div class="form-group col-md-12">
            <label for="Excerpt" class="secondaryField">Excerpt (Optional)</label>
            <textarea class="form-control" placeholder="" 
            asp-for="NewArticle.Excerpt"></textarea>
        </div>
        @* Upload file *@
        <div class="col-md-12">
            <div class="form-group">
                <label>Upload Files</label>
                <input type="file" name="files" multiple id="file-input"
                       onchange="insertFiles()"/>
            </div>
        </div>
        @* Save or Publish*@
        <div class="col-md-12">
            <input type="submit" name="save" class="btn btn-primary btn-sm"
                   value="Save Draft" asp-page-handler="SaveDraft"/>
            <input type="submit" name="publish" class="btn btn-primary btn-sm"
                   value="Publish" asp-page-handler="Publish"/>
        </div>
    </div>
</form>

@section Scripts 
{
}